name: Daily_Fudan_OCRversion

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          pip install opencv-python
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 30-1000 -n 1)
        
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} KEY=${{ secrets.KEY }} python3 main.py
